/**
 * @overview
 *
 * @since 0.1.0
 * @author Stefan Rimaila <stefan@rimaila.fi>
 */

/** @type {Dockyard.Action} */
export default {
  // Construction
  CREATE_ITEM: 'CREATE_ITEM',
  UPDATE_ITEM: 'UPDATE_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',

  CREATE_SHIP: 'CREATE_SHIP',
  CREATE_SHIP_FINISH: 'CREATE_SHIP_FINISH',
  UPDATE_SHIP: 'UPDATE_SHIP',
  DELETE_SHIP: 'DELETE_SHIP',

  // Player state
  UPDATE_PLAYER_STATE: 'UPDATE_PLAYER_STATE',
  UPDATE_PLAYER_PROFILE: 'UPDATE_PLAYER_PROFILE',

  // Game
  CREATE_BASE_DATA: 'CREATE_BASE_DATA',
  UPDATE_BASE_DATA: 'UPDATE_BASE_DATA',
  UPDATE_QUEST_LIST: 'UPDATE_QUEST_LIST',
  UPDATE_GAME_STATE: 'UPDATE_GAME_STATE'
};